project_id = "ajkhsdxhbbkrtunfxhbi"

[functions.generate-seo-page]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.seed-pages]
verify_jwt = false

[functions.fetch-spotify-images]
verify_jwt = false

[functions.fetch-samples]
verify_jwt = false
