import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

const SEEDS: { slug: string; page_type: string }[] = [
  // ── Songs (200) ──
  { slug: "bohemian-rhapsody", page_type: "song" },
  { slug: "blinding-lights", page_type: "song" },
  { slug: "smells-like-teen-spirit", page_type: "song" },
  { slug: "redbone", page_type: "song" },
  { slug: "somebody-that-i-used-to-know", page_type: "song" },
  { slug: "midnight-city", page_type: "song" },
  { slug: "video-games", page_type: "song" },
  { slug: "ivy", page_type: "song" },
  { slug: "let-it-happen", page_type: "song" },
  { slug: "electric-feel", page_type: "song" },
  { slug: "do-i-wanna-know", page_type: "song" },
  { slug: "skinny-love", page_type: "song" },
  { slug: "get-lucky", page_type: "song" },
  { slug: "somebody-else", page_type: "song" },
  { slug: "take-me-out", page_type: "song" },
  { slug: "pumped-up-kicks", page_type: "song" },
  { slug: "take-on-me", page_type: "song" },
  { slug: "hotline-bling", page_type: "song" },
  { slug: "space-oddity", page_type: "song" },
  { slug: "come-as-you-are", page_type: "song" },
  { slug: "fast-car", page_type: "song" },
  { slug: "feel-good-inc", page_type: "song" },
  { slug: "no-surprises", page_type: "song" },
  { slug: "budapest", page_type: "song" },
  { slug: "creep", page_type: "song" },
  { slug: "wish-you-were-here", page_type: "song" },
  { slug: "dreams", page_type: "song" },
  { slug: "mr-brightside", page_type: "song" },
  { slug: "heart-of-gold", page_type: "song" },
  { slug: "under-pressure", page_type: "song" },
  { slug: "lose-yourself", page_type: "song" },
  { slug: "stairway-to-heaven", page_type: "song" },
  { slug: "a-case-of-you", page_type: "song" },
  { slug: "pink-white", page_type: "song" },
  { slug: "the-less-i-know-the-better", page_type: "song" },
  { slug: "hey-ya", page_type: "song" },
  { slug: "stan", page_type: "song" },
  { slug: "jolene", page_type: "song" },
  { slug: "hallelujah", page_type: "song" },
  { slug: "heroes", page_type: "song" },
  { slug: "purple-rain", page_type: "song" },
  { slug: "africa", page_type: "song" },
  { slug: "dont-stop-me-now", page_type: "song" },
  { slug: "superstition", page_type: "song" },
  { slug: "imagine", page_type: "song" },
  { slug: "hotel-california", page_type: "song" },
  { slug: "sweet-child-o-mine", page_type: "song" },
  { slug: "like-a-rolling-stone", page_type: "song" },
  { slug: "dancing-queen", page_type: "song" },
  { slug: "karma-police", page_type: "song" },
  { slug: "november-rain", page_type: "song" },
  { slug: "fly-me-to-the-moon", page_type: "song" },
  { slug: "a-day-in-the-life", page_type: "song" },
  { slug: "roxanne", page_type: "song" },
  { slug: "landslide", page_type: "song" },
  { slug: "life-on-mars", page_type: "song" },
  { slug: "fade-into-you", page_type: "song" },
  { slug: "lovefool", page_type: "song" },
  { slug: "torn", page_type: "song" },
  { slug: "everywhere", page_type: "song" },
  { slug: "losing-my-religion", page_type: "song" },
  { slug: "champagne-supernova", page_type: "song" },
  { slug: "nuthin-but-a-g-thang", page_type: "song" },
  { slug: "motion-sickness", page_type: "song" },
  { slug: "waves", page_type: "song" },
  { slug: "heat-waves", page_type: "song" },
  { slug: "young-folks", page_type: "song" },
  { slug: "ribs", page_type: "song" },
  { slug: "myth", page_type: "song" },
  { slug: "never-gonna-give-you-up", page_type: "song" },
  { slug: "summertime-sadness", page_type: "song" },
  { slug: "alright", page_type: "song" },
  { slug: "nights", page_type: "song" },
  { slug: "black-dog", page_type: "song" },
  { slug: "comfortably-numb", page_type: "song" },
  { slug: "bitter-sweet-symphony", page_type: "song" },
  { slug: "zombie", page_type: "song" },
  { slug: "where-is-my-mind", page_type: "song" },
  { slug: "lucky", page_type: "song" },
  { slug: "agnes", page_type: "song" },
  // New songs
  { slug: "bad-guy", page_type: "song" },
  { slug: "ocean-eyes", page_type: "song" },
  { slug: "drivers-license", page_type: "song" },
  { slug: "good-4-u", page_type: "song" },
  { slug: "anti-hero", page_type: "song" },
  { slug: "cruel-summer", page_type: "song" },
  { slug: "all-too-well", page_type: "song" },
  { slug: "love-story", page_type: "song" },
  { slug: "shake-it-off", page_type: "song" },
  { slug: "cardigan", page_type: "song" },
  { slug: "exile", page_type: "song" },
  { slug: "august", page_type: "song" },
  { slug: "seven-nation-army", page_type: "song" },
  { slug: "black-hole-sun", page_type: "song" },
  { slug: "smooth-criminal", page_type: "song" },
  { slug: "thriller", page_type: "song" },
  { slug: "billie-jean", page_type: "song" },
  { slug: "beat-it", page_type: "song" },
  { slug: "rolling-in-the-deep", page_type: "song" },
  { slug: "someone-like-you", page_type: "song" },
  { slug: "hello", page_type: "song" },
  { slug: "skyfall", page_type: "song" },
  { slug: "formation", page_type: "song" },
  { slug: "crazy-in-love", page_type: "song" },
  { slug: "halo", page_type: "song" },
  { slug: "lemonade", page_type: "song" },
  { slug: "run-the-world-girls", page_type: "song" },
  { slug: "gold-digger", page_type: "song" },
  { slug: "stronger", page_type: "song" },
  { slug: "all-of-the-lights", page_type: "song" },
  { slug: "runaway", page_type: "song" },
  { slug: "ultralight-beam", page_type: "song" },
  { slug: "flashing-lights", page_type: "song" },
  { slug: "power", page_type: "song" },
  { slug: "one-dance", page_type: "song" },
  { slug: "gods-plan", page_type: "song" },
  { slug: "in-my-feelings", page_type: "song" },
  { slug: "started-from-the-bottom", page_type: "song" },
  { slug: "sicko-mode", page_type: "song" },
  { slug: "goosebumps", page_type: "song" },
  { slug: "antidote", page_type: "song" },
  { slug: "humble", page_type: "song" },
  { slug: "dna", page_type: "song" },
  { slug: "money-trees", page_type: "song" },
  { slug: "swimming-pools", page_type: "song" },
  { slug: "backseat-freestyle", page_type: "song" },
  { slug: "good-kid", page_type: "song" },
  { slug: "m-a-a-d-city", page_type: "song" },
  { slug: "poetic-justice", page_type: "song" },
  { slug: "loyalty", page_type: "song" },
  { slug: "element", page_type: "song" },
  { slug: "love-kdot", page_type: "song" },
  { slug: "do-re-mi", page_type: "song" },
  { slug: "see-you-again", page_type: "song" },
  { slug: "rockstar", page_type: "song" },
  { slug: "sunflower", page_type: "song" },
  { slug: "circles", page_type: "song" },
  { slug: "the-search", page_type: "song" },
  { slug: "lucid-dreams", page_type: "song" },
  { slug: "legends-never-die", page_type: "song" },
  { slug: "changes", page_type: "song" },
  { slug: "sad", page_type: "song" },
  { slug: "what-a-time", page_type: "song" },
  { slug: "peaches", page_type: "song" },
  { slug: "stay", page_type: "song" },
  { slug: "ghost", page_type: "song" },
  { slug: "montero", page_type: "song" },
  { slug: "industry-baby", page_type: "song" },
  { slug: "thats-what-i-want", page_type: "song" },
  { slug: "solar-power", page_type: "song" },
  { slug: "royals", page_type: "song" },
  { slug: "green-light", page_type: "song" },
  { slug: "liability", page_type: "song" },
  { slug: "team", page_type: "song" },
  { slug: "perfect-places", page_type: "song" },
  { slug: "writer-in-the-dark", page_type: "song" },
  { slug: "buzzcut-season", page_type: "song" },
  { slug: "still-sane", page_type: "song" },
  { slug: "white-teeth-teens", page_type: "song" },
  { slug: "glory-and-gore", page_type: "song" },
  { slug: "hurricane", page_type: "song" },
  { slug: "odd-look", page_type: "song" },
  { slug: "pray-for-me", page_type: "song" },
  { slug: "starboy", page_type: "song" },
  { slug: "save-your-tears", page_type: "song" },
  { slug: "cant-feel-my-face", page_type: "song" },
  { slug: "earned-it", page_type: "song" },
  { slug: "the-hills", page_type: "song" },
  { slug: "often", page_type: "song" },
  { slug: "belong-to-the-world", page_type: "song" },
  { slug: "kissland", page_type: "song" },
  { slug: "wicked-games", page_type: "song" },
  { slug: "call-out-my-name", page_type: "song" },
  { slug: "heartless", page_type: "song" },
  { slug: "blinding-lights-weeknd", page_type: "song" },
  { slug: "after-hours", page_type: "song" },
  { slug: "scared-to-live", page_type: "song" },
  { slug: "alone-again", page_type: "song" },
  { slug: "snowchild", page_type: "song" },
  { slug: "faith", page_type: "song" },
  { slug: "repeat-after-me", page_type: "song" },
  { slug: "best-i-ever-had", page_type: "song" },
  { slug: "marvin-room", page_type: "song" },
  { slug: "take-care", page_type: "song" },
  { slug: "headlines", page_type: "song" },
  { slug: "marvins-room", page_type: "song" },
  { slug: "hold-on-were-going-home", page_type: "song" },
  { slug: "pound-cake", page_type: "song" },
  { slug: "trophies", page_type: "song" },
  { slug: "worst-behavior", page_type: "song" },
  { slug: "too-much", page_type: "song" },
  { slug: "from-time", page_type: "song" },
  { slug: "connect", page_type: "song" },
  { slug: "cameras", page_type: "song" },
  { slug: "look-what-youve-done", page_type: "song" },
  { slug: "furthest-thing", page_type: "song" },
  { slug: "jaded", page_type: "song" },
  { slug: "passionfruit", page_type: "song" },
  { slug: "get-it-together", page_type: "song" },

  // ── Artists (150) ──
  { slug: "taylor-swift", page_type: "artist" },
  { slug: "tame-impala", page_type: "artist" },
  { slug: "frank-ocean", page_type: "artist" },
  { slug: "radiohead", page_type: "artist" },
  { slug: "lana-del-rey", page_type: "artist" },
  { slug: "kendrick-lamar", page_type: "artist" },
  { slug: "arctic-monkeys", page_type: "artist" },
  { slug: "sza", page_type: "artist" },
  { slug: "bon-iver", page_type: "artist" },
  { slug: "daft-punk", page_type: "artist" },
  { slug: "the-weeknd", page_type: "artist" },
  { slug: "billie-eilish", page_type: "artist" },
  { slug: "fleetwood-mac", page_type: "artist" },
  { slug: "tyler-the-creator", page_type: "artist" },
  { slug: "pink-floyd", page_type: "artist" },
  { slug: "hozier", page_type: "artist" },
  { slug: "childish-gambino", page_type: "artist" },
  { slug: "david-bowie", page_type: "artist" },
  { slug: "gorillaz", page_type: "artist" },
  { slug: "mac-demarco", page_type: "artist" },
  { slug: "phoebe-bridgers", page_type: "artist" },
  { slug: "nirvana", page_type: "artist" },
  { slug: "the-1975", page_type: "artist" },
  { slug: "beach-house", page_type: "artist" },
  { slug: "steve-lacy", page_type: "artist" },
  { slug: "mgmt", page_type: "artist" },
  { slug: "amy-winehouse", page_type: "artist" },
  { slug: "glass-animals", page_type: "artist" },
  { slug: "drake", page_type: "artist" },
  { slug: "kanye-west", page_type: "artist" },
  { slug: "joni-mitchell", page_type: "artist" },
  { slug: "queen", page_type: "artist" },
  { slug: "the-strokes", page_type: "artist" },
  { slug: "mac-miller", page_type: "artist" },
  { slug: "mitski", page_type: "artist" },
  { slug: "adele", page_type: "artist" },
  { slug: "led-zeppelin", page_type: "artist" },
  { slug: "prince", page_type: "artist" },
  { slug: "the-beatles", page_type: "artist" },
  { slug: "stevie-wonder", page_type: "artist" },
  { slug: "outkast", page_type: "artist" },
  { slug: "the-cure", page_type: "artist" },
  { slug: "depeche-mode", page_type: "artist" },
  { slug: "the-smiths", page_type: "artist" },
  { slug: "joy-division", page_type: "artist" },
  { slug: "talking-heads", page_type: "artist" },
  { slug: "r-e-m", page_type: "artist" },
  { slug: "oasis", page_type: "artist" },
  { slug: "blur", page_type: "artist" },
  { slug: "the-national", page_type: "artist" },
  { slug: "sufjan-stevens", page_type: "artist" },
  { slug: "elliott-smith", page_type: "artist" },
  { slug: "fiona-apple", page_type: "artist" },
  { slug: "bjork", page_type: "artist" },
  { slug: "portishead", page_type: "artist" },
  { slug: "massive-attack", page_type: "artist" },
  { slug: "cocteau-twins", page_type: "artist" },
  { slug: "kate-bush", page_type: "artist" },
  { slug: "lorde", page_type: "artist" },
  { slug: "clairo", page_type: "artist" },
  { slug: "weyes-blood", page_type: "artist" },
  { slug: "khruangbin", page_type: "artist" },
  { slug: "japanese-breakfast", page_type: "artist" },
  { slug: "the-war-on-drugs", page_type: "artist" },
  { slug: "alvvays", page_type: "artist" },
  { slug: "men-i-trust", page_type: "artist" },
  { slug: "cigarettes-after-sex", page_type: "artist" },
  { slug: "j-cole", page_type: "artist" },
  { slug: "travis-scott", page_type: "artist" },
  { slug: "post-malone", page_type: "artist" },
  { slug: "juice-wrld", page_type: "artist" },
  { slug: "xxxtentacion", page_type: "artist" },
  { slug: "lil-uzi-vert", page_type: "artist" },
  { slug: "future", page_type: "artist" },
  { slug: "young-thug", page_type: "artist" },
  { slug: "21-savage", page_type: "artist" },
  { slug: "gunna", page_type: "artist" },
  { slug: "olivia-rodrigo", page_type: "artist" },
  { slug: "doja-cat", page_type: "artist" },
  { slug: "harry-styles", page_type: "artist" },
  { slug: "bad-bunny", page_type: "artist" },
  { slug: "the-kid-laroi", page_type: "artist" },
  { slug: "justin-bieber", page_type: "artist" },
  { slug: "ariana-grande", page_type: "artist" },
  { slug: "dua-lipa", page_type: "artist" },
  { slug: "lizzo", page_type: "artist" },
  { slug: "cardi-b", page_type: "artist" },
  { slug: "megan-thee-stallion", page_type: "artist" },
  { slug: "nicki-minaj", page_type: "artist" },
  { slug: "beyonce", page_type: "artist" },
  { slug: "rihanna", page_type: "artist" },
  { slug: "michael-jackson", page_type: "artist" },
  { slug: "madonna", page_type: "artist" },
  { slug: "bruce-springsteen", page_type: "artist" },
  { slug: "bob-dylan", page_type: "artist" },
  { slug: "neil-young", page_type: "artist" },
  { slug: "joni-mitchell", page_type: "artist" },
  { slug: "james-brown", page_type: "artist" },
  { slug: "aretha-franklin", page_type: "artist" },
  { slug: "marvin-gaye", page_type: "artist" },
  { slug: "whitney-houston", page_type: "artist" },
  { slug: "elton-john", page_type: "artist" },
  { slug: "paul-simon", page_type: "artist" },
  { slug: "simon-and-garfunkel", page_type: "artist" },
  { slug: "the-rolling-stones", page_type: "artist" },
  { slug: "the-doors", page_type: "artist" },
  { slug: "jimi-hendrix", page_type: "artist" },
  { slug: "janis-joplin", page_type: "artist" },
  { slug: "the-velvet-underground", page_type: "artist" },
  { slug: "lou-reed", page_type: "artist" },
  { slug: "patti-smith", page_type: "artist" },
  { slug: "blondie", page_type: "artist" },
  { slug: "the-clash", page_type: "artist" },
  { slug: "the-pixies", page_type: "artist" },
  { slug: "sonic-youth", page_type: "artist" },
  { slug: "my-bloody-valentine", page_type: "artist" },
  { slug: "neutral-milk-hotel", page_type: "artist" },
  { slug: "built-to-spill", page_type: "artist" },
  { slug: "pavement", page_type: "artist" },
  { slug: "modest-mouse", page_type: "artist" },
  { slug: "death-cab-for-cutie", page_type: "artist" },
  { slug: "iron-and-wine", page_type: "artist" },
  { slug: "bright-eyes", page_type: "artist" },
  { slug: "the-shins", page_type: "artist" },
  { slug: "fleet-foxes", page_type: "artist" },
  { slug: "vampire-weekend", page_type: "artist" },
  { slug: "lcd-soundsystem", page_type: "artist" },
  { slug: "animal-collective", page_type: "artist" },
  { slug: "grizzly-bear", page_type: "artist" },
  { slug: "dirty-projectors", page_type: "artist" },
  { slug: "spoon", page_type: "artist" },
  { slug: "wilco", page_type: "artist" },
  { slug: "yo-la-tengo", page_type: "artist" },
  { slug: "belle-and-sebastian", page_type: "artist" },
  { slug: "the-xx", page_type: "artist" },
  { slug: "alt-j", page_type: "artist" },
  { slug: "foals", page_type: "artist" },
  { slug: "interpol", page_type: "artist" },
  { slug: "editors", page_type: "artist" },
  { slug: "the-horrors", page_type: "artist" },
  { slug: "warpaint", page_type: "artist" },
  { slug: "chromatics", page_type: "artist" },
  { slug: "real-estate", page_type: "artist" },
  { slug: "sun-kil-moon", page_type: "artist" },
  { slug: "pinegrove", page_type: "artist" },
  { slug: "boygenius", page_type: "artist" },
  { slug: "snail-mail", page_type: "artist" },
  { slug: "soccer-mommy", page_type: "artist" },
  { slug: "alex-g", page_type: "artist" },
  { slug: "illuminati-hotties", page_type: "artist" },
  { slug: "big-thief", page_type: "artist" },
  { slug: "adrianne-lenker", page_type: "artist" },

  // ── Vibes (100) ──
  { slug: "music-for-night-driving", page_type: "vibe" },
  { slug: "golden-hour-chill", page_type: "vibe" },
  { slug: "rainy-lo-fi", page_type: "vibe" },
  { slug: "dark-academia-playlist", page_type: "vibe" },
  { slug: "main-character-energy", page_type: "vibe" },
  { slug: "chill-lo-fi-study-beats", page_type: "vibe" },
  { slug: "late-night-sad-songs", page_type: "vibe" },
  { slug: "getting-over-a-breakup", page_type: "vibe" },
  { slug: "sunday-morning-coffee", page_type: "vibe" },
  { slug: "summer-road-trip", page_type: "vibe" },
  { slug: "90s-nostalgia", page_type: "vibe" },
  { slug: "indie-coffee-shop", page_type: "vibe" },
  { slug: "workout-hype", page_type: "vibe" },
  { slug: "ethereal-dreamy", page_type: "vibe" },
  { slug: "cozy-winter-evening", page_type: "vibe" },
  { slug: "beach-sunset-vibes", page_type: "vibe" },
  { slug: "melancholy-but-beautiful", page_type: "vibe" },
  { slug: "feel-good-upbeat", page_type: "vibe" },
  { slug: "midnight-jazz", page_type: "vibe" },
  { slug: "cyberpunk-synthwave", page_type: "vibe" },
  { slug: "acoustic-campfire", page_type: "vibe" },
  { slug: "falling-in-love", page_type: "vibe" },
  { slug: "songs-that-feel-like-floating", page_type: "vibe" },
  { slug: "villain-era-playlist", page_type: "vibe" },
  { slug: "childhood-nostalgia", page_type: "vibe" },
  { slug: "4am-thoughts", page_type: "vibe" },
  { slug: "city-pop-aesthetic", page_type: "vibe" },
  { slug: "songs-for-a-movie-soundtrack", page_type: "vibe" },
  { slug: "slow-burn-romance", page_type: "vibe" },
  { slug: "desert-highway-rock", page_type: "vibe" },
  { slug: "foggy-morning-walk", page_type: "vibe" },
  { slug: "existential-crisis-playlist", page_type: "vibe" },
  { slug: "sapphic-indie", page_type: "vibe" },
  { slug: "cottagecore-folk", page_type: "vibe" },
  { slug: "songs-that-make-you-feel-powerful", page_type: "vibe" },
  { slug: "liminal-space-music", page_type: "vibe" },
  { slug: "sunset-on-the-rooftop", page_type: "vibe" },
  { slug: "old-soul-playlist", page_type: "vibe" },
  { slug: "2000s-pop-throwback", page_type: "vibe" },
  { slug: "songs-for-stargazing", page_type: "vibe" },
  { slug: "rainy-day-acoustic", page_type: "vibe" },
  { slug: "after-party-comedown", page_type: "vibe" },
  { slug: "shower-singing-bangers", page_type: "vibe" },
  { slug: "songs-that-feel-like-autumn", page_type: "vibe" },
  { slug: "driving-through-the-city-at-night", page_type: "vibe" },
  { slug: "hauntingly-beautiful", page_type: "vibe" },
  { slug: "songs-that-feel-like-a-warm-hug", page_type: "vibe" },
  { slug: "90s-alternative-deep-cuts", page_type: "vibe" },
  { slug: "bittersweet-graduation", page_type: "vibe" },
  { slug: "psychedelic-journey", page_type: "vibe" },
  { slug: "windows-down-summer", page_type: "vibe" },
  { slug: "crying-in-the-car", page_type: "vibe" },
  { slug: "songs-that-hit-different-at-night", page_type: "vibe" },
  { slug: "pre-game-energy", page_type: "vibe" },
  { slug: "studying-in-the-library", page_type: "vibe" },
  { slug: "healing-era", page_type: "vibe" },
  { slug: "hot-girl-summer", page_type: "vibe" },
  { slug: "sad-girl-autumn", page_type: "vibe" },
  { slug: "soft-boy-playlist", page_type: "vibe" },
  { slug: "grunge-revival", page_type: "vibe" },
  { slug: "new-wave-classics", page_type: "vibe" },
  { slug: "post-punk-revival", page_type: "vibe" },
  { slug: "shoegaze-dream", page_type: "vibe" },
  { slug: "ambient-focus", page_type: "vibe" },
  { slug: "jazz-for-thinking", page_type: "vibe" },
  { slug: "soul-for-the-heartbroken", page_type: "vibe" },
  { slug: "r-and-b-slow-jams", page_type: "vibe" },
  { slug: "hip-hop-golden-age", page_type: "vibe" },
  { slug: "trap-bangers", page_type: "vibe" },
  { slug: "conscious-rap", page_type: "vibe" },
  { slug: "bedroom-pop-vibes", page_type: "vibe" },
  { slug: "indie-folk-for-introverts", page_type: "vibe" },
  { slug: "late-capitalism-playlist", page_type: "vibe" },
  { slug: "songs-about-growing-up", page_type: "vibe" },
  { slug: "songs-about-moving-on", page_type: "vibe" },
  { slug: "songs-about-home", page_type: "vibe" },
  { slug: "songs-about-loneliness", page_type: "vibe" },
  { slug: "songs-about-identity", page_type: "vibe" },
  { slug: "songs-about-mental-health", page_type: "vibe" },
  { slug: "songs-about-the-ocean", page_type: "vibe" },
  { slug: "songs-about-cities", page_type: "vibe" },
  { slug: "songs-about-the-apocalypse", page_type: "vibe" },
  { slug: "music-that-sounds-like-a-fever-dream", page_type: "vibe" },
  { slug: "music-that-sounds-like-nostalgia", page_type: "vibe" },
  { slug: "music-that-sounds-like-heartbreak", page_type: "vibe" },
  { slug: "music-that-sounds-like-hope", page_type: "vibe" },
  { slug: "perfect-for-a-montage", page_type: "vibe" },
  { slug: "songs-for-the-gym", page_type: "vibe" },
  { slug: "songs-for-yoga", page_type: "vibe" },
  { slug: "songs-for-cooking", page_type: "vibe" },
  { slug: "songs-for-falling-asleep", page_type: "vibe" },
  { slug: "songs-for-waking-up", page_type: "vibe" },
  { slug: "songs-for-a-first-date", page_type: "vibe" },
  { slug: "songs-for-a-breakup-party", page_type: "vibe" },
  { slug: "songs-for-feeling-unstoppable", page_type: "vibe" },
  { slug: "songs-for-feeling-small", page_type: "vibe" },
  { slug: "indie-sleaze-revival", page_type: "vibe" },
  { slug: "nu-metal-throwback", page_type: "vibe" },
  { slug: "emo-revival", page_type: "vibe" },
  { slug: "folk-punk-energy", page_type: "vibe" },

  // ── Producers (50) ──
  { slug: "rick-rubin", page_type: "producer" },
  { slug: "quincy-jones", page_type: "producer" },
  { slug: "pharrell-williams", page_type: "producer" },
  { slug: "kanye-west", page_type: "producer" },
  { slug: "metro-boomin", page_type: "producer" },
  { slug: "mike-dean", page_type: "producer" },
  { slug: "hit-boy", page_type: "producer" },
  { slug: "jack-antonoff", page_type: "producer" },
  { slug: "max-martin", page_type: "producer" },
  { slug: "timbaland", page_type: "producer" },
  { slug: "neptunes", page_type: "producer" },
  { slug: "dr-dre", page_type: "producer" },
  { slug: "j-dilla", page_type: "producer" },
  { slug: "madlib", page_type: "producer" },
  { slug: "flying-lotus", page_type: "producer" },
  { slug: "kaytranada", page_type: "producer" },
  { slug: "thundercat", page_type: "producer" },
  { slug: "kenny-beats", page_type: "producer" },
  { slug: "cole-bennett", page_type: "producer" },
  { slug: "tde-collective", page_type: "producer" },
  { slug: "sounwave", page_type: "producer" },
  { slug: "no-i-d", page_type: "producer" },
  { slug: "just-blaze", page_type: "producer" },
  { slug: "9th-wonder", page_type: "producer" },
  { slug: "dj-premier", page_type: "producer" },
  { slug: "pete-rock", page_type: "producer" },
  { slug: "alchemist", page_type: "producer" },
  { slug: "evidence", page_type: "producer" },
  { slug: "araab-muzik", page_type: "producer" },
  { slug: "lex-luger", page_type: "producer" },
  { slug: "southside", page_type: "producer" },
  { slug: "wheezy", page_type: "producer" },
  { slug: "murda-beatz", page_type: "producer" },
  { slug: "cubeatz", page_type: "producer" },
  { slug: "tay-keith", page_type: "producer" },
  { slug: "scott-storch", page_type: "producer" },
  { slug: "swizz-beatz", page_type: "producer" },
  { slug: "mark-ronson", page_type: "producer" },
  { slug: "danger-mouse", page_type: "producer" },
  { slug: "diplo", page_type: "producer" },
  { slug: "skrillex", page_type: "producer" },
  { slug: "four-tet", page_type: "producer" },
  { slug: "burial", page_type: "producer" },
  { slug: "aphex-twin", page_type: "producer" },
  { slug: "boards-of-canada", page_type: "producer" },
  { slug: "brian-eno", page_type: "producer" },
  { slug: "tony-visconti", page_type: "producer" },
  { slug: "george-martin", page_type: "producer" },
  { slug: "nigel-godrich", page_type: "producer" },
  { slug: "kevin-parker", page_type: "producer" },
];

// Deduplicate
const seen = new Set<string>();
const UNIQUE_SEEDS = SEEDS.filter((s) => {
  const key = `${s.page_type}:${s.slug}`;
  if (seen.has(key)) return false;
  seen.add(key);
  return true;
});

const DELAY_MS = 2500;

function sleep(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const body = await req.json().catch(() => ({}));
    const limit = Math.min(Math.max(body.limit || 10, 1), 50);
    const offset = Math.max(body.offset || 0, 0);

    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseServiceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    // Get existing pages
    const { data: existing } = await supabase
      .from("seo_pages")
      .select("slug, page_type");

    const existingSet = new Set(
      (existing || []).map((p: any) => `${p.page_type}:${p.slug}`)
    );

    // Slice the seed list from offset
    const window = UNIQUE_SEEDS.slice(offset, offset + limit);
    const toGenerate = window.filter((s) => !existingSet.has(`${s.page_type}:${s.slug}`));
    const alreadyExist = window.filter((s) => existingSet.has(`${s.page_type}:${s.slug}`));

    console.log(`Batch: offset=${offset}, limit=${limit}, window=${window.length}, toGenerate=${toGenerate.length}, skipped=${alreadyExist.length}`);

    let created = 0;
    let failed = 0;
    const errors: { slug: string; page_type: string; error: string }[] = [];

    // Process one at a time to stay within timeout
    for (let i = 0; i < toGenerate.length; i++) {
      const seed = toGenerate[i];
      try {
        const res = await fetch(`${supabaseUrl}/functions/v1/generate-seo-page`, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${supabaseServiceKey}`,
          },
          body: JSON.stringify(seed),
        });

        if (res.status === 429) {
          errors.push({ ...seed, error: "rate_limited" });
          failed++;
          continue;
        }

        const data = await res.json();
        if (data.error) {
          errors.push({ ...seed, error: data.error });
          failed++;
        } else {
          created++;
          console.log(`Created: ${seed.page_type}/${seed.slug} (${i + 1}/${toGenerate.length})`);
        }
      } catch (e) {
        errors.push({ ...seed, error: e.message });
        failed++;
      }

      if (i < toGenerate.length - 1) {
        await sleep(DELAY_MS);
      }
    }

    const nextOffset = offset + limit;
    const remaining = Math.max(UNIQUE_SEEDS.length - nextOffset, 0);
    const done = nextOffset >= UNIQUE_SEEDS.length;

    const summary = {
      total_seeds: UNIQUE_SEEDS.length,
      offset,
      limit,
      attempted: toGenerate.length,
      created,
      skipped: alreadyExist.length,
      failed,
      errors: errors.length > 0 ? errors : undefined,
      next_offset: done ? null : nextOffset,
      remaining,
      done,
    };

    console.log(`Result: ${JSON.stringify({ ...summary, errors: undefined })}`);

    return new Response(JSON.stringify(summary), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (e) {
    console.error("seed-pages error:", e);
    return new Response(
      JSON.stringify({ error: e instanceof Error ? e.message : "Unknown error" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
