-- Seed descriptor_registry with full Sonic DNA vocabulary
-- Safe to run multiple times (upsert on slug)

INSERT INTO public.descriptor_registry
  (slug, label, category, description, tier, is_public, is_clickable, is_seo_enabled)
VALUES
  ('slow-burn', 'Slow Burn', 'tempo_feel', 'Gradual, unhurried pacing that builds tension without rushing', 1, true, true, true),
  ('laid-back', 'Laid Back', 'tempo_feel', 'Relaxed, behind-the-beat groove that feels effortless', 1, true, true, true),
  ('midtempo', 'Midtempo', 'tempo_feel', 'Moderate pace — not slow, not urgent, steady and purposeful', 2, true, false, false),
  ('driving', 'Driving', 'tempo_feel', 'Forward momentum that propels the listener continuously', 1, true, true, true),
  ('urgent', 'Urgent', 'tempo_feel', 'High energy pace that conveys immediacy and intensity', 2, true, false, false),
  ('propulsive', 'Propulsive', 'tempo_feel', 'Rhythmic momentum that continuously pushes forward', 2, true, false, false),
  ('floating', 'Floating', 'tempo_feel', 'Untethered, weightless tempo feel with loose rhythmic gravity', 1, true, true, true),
  ('steady', 'Steady', 'tempo_feel', 'Consistent, reliable pulse without acceleration or hesitation', 2, true, false, false),
  ('straight', 'Straight', 'groove', 'Even, on-the-grid rhythmic feel without swing or syncopation', 2, true, false, false),
  ('swung', 'Swung', 'groove', 'Jazz-influenced triplet feel that gives rhythm a lilting quality', 2, true, false, false),
  ('syncopated', 'Syncopated', 'groove', 'Accents fall off the main beat, creating rhythmic surprise', 2, true, false, false),
  ('shuffling', 'Shuffling', 'groove', 'Loose, slightly swung groove reminiscent of blues or classic soul', 2, true, false, false),
  ('pulsing', 'Pulsing', 'groove', 'Repetitive, heartbeat-like rhythmic drive that feels hypnotic', 1, true, true, true),
  ('hypnotic', 'Hypnotic', 'groove', 'Repetitive rhythmic pattern designed to induce a trance-like state', 1, true, true, true),
  ('bouncy', 'Bouncy', 'groove', 'Playful, spring-loaded groove with an upward rhythmic feel', 1, true, true, true),
  ('stuttering', 'Stuttering', 'groove', 'Interrupted or fragmented rhythmic pattern with deliberate breaks', 2, true, false, false),
  ('gliding', 'Gliding', 'groove', 'Smooth, frictionless rhythmic movement that feels effortless', 2, true, false, false),
  ('marching', 'Marching', 'groove', 'Militaristic, deliberate pulse with an insistent forward drive', 2, true, false, false),
  ('rolling', 'Rolling', 'groove', 'Continuous, wave-like rhythmic motion that builds organically', 2, true, false, false),
  ('locked-in', 'Locked In', 'groove', 'Extremely tight rhythmic pocket where all elements align precisely', 2, true, false, false),
  ('crisp', 'Crisp', 'drum_character', 'Clean, defined drum sounds with sharp transient attack', 2, true, false, false),
  ('dusty', 'Dusty', 'drum_character', 'Slightly degraded, vintage-sounding drums with analog warmth', 1, true, true, true),
  ('punchy', 'Punchy', 'drum_character', 'Impactful drums with strong low-mid presence and immediate attack', 2, true, false, false),
  ('clipped', 'Clipped', 'drum_character', 'Intentionally shortened drum sounds, tight and dry', 3, false, false, false),
  ('roomy', 'Roomy', 'drum_character', 'Drums with natural reverb suggesting a large physical space', 2, true, false, false),
  ('electronic', 'Electronic', 'drum_character', 'Synthesized or programmed drum sounds with digital precision', 2, true, false, false),
  ('live-kit', 'Live Kit', 'drum_character', 'Acoustic drum sounds recorded with natural room response', 2, true, false, false),
  ('808-heavy', '808 Heavy', 'drum_character', 'TR-808 bass drum dominates with booming sub-frequency kicks', 1, true, true, true),
  ('breakbeat-driven', 'Breakbeat', 'drum_character', 'Sampled drum breaks form the rhythmic foundation', 1, true, true, true),
  ('clap-forward', 'Clap Forward', 'drum_character', 'Snare clap mix sits prominently in the high-mid frequency range', 3, false, false, false),
  ('gated', 'Gated', 'drum_character', 'Gated reverb effect on snares, characteristic of 80s production', 2, true, false, false),
  ('skeletal', 'Skeletal', 'drum_character', 'Minimal drum arrangement with deliberate space between hits', 2, true, false, false),
  ('sub-heavy', 'Sub Heavy', 'bass_character', 'Dominant low-frequency bass that you feel more than hear', 1, true, true, true),
  ('melodic-bass', 'Melodic Bass', 'bass_character', 'Bass line that carries harmonic interest and melodic motion', 2, true, false, false),
  ('rubbery', 'Rubbery', 'bass_character', 'Elastic, bouncing bass with a playful, slightly loose quality', 2, true, false, false),
  ('droning', 'Droning', 'bass_character', 'Sustained bass note or pedal tone creating harmonic tension', 2, true, false, false),
  ('warm-bass', 'Warm Bass', 'bass_character', 'Bass with rounded low-mid presence, smooth and full-bodied', 2, true, false, false),
  ('distorted', 'Distorted', 'bass_character', 'Overdriven bass with harmonic saturation and gritty texture', 2, true, false, false),
  ('restrained', 'Restrained', 'bass_character', 'Bass sits back in the mix, providing support without dominating', 2, true, false, false),
  ('funky', 'Funky', 'bass_character', 'Syncopated, groove-forward bass with soul and R&B character', 1, true, true, true),
  ('syrupy', 'Syrupy', 'bass_character', 'Thick, slow-moving bass with a viscous, heavy quality', 2, true, false, false),
  ('synth-bass', 'Synth Bass', 'bass_character', 'Electronically synthesized bass with sharp, precise attack', 2, true, false, false),
  ('minor-key', 'Minor Key', 'harmonic_color', 'Tonal center built on a minor scale, often conveying melancholy', 2, true, false, false),
  ('major-key', 'Major Key', 'harmonic_color', 'Tonal center built on a major scale, often bright or hopeful', 2, true, false, false),
  ('jazzy', 'Jazzy', 'harmonic_color', 'Extended chord voicings with jazz harmony influence', 1, true, true, true),
  ('lush', 'Lush', 'harmonic_color', 'Dense, rich harmonic layers that feel immersive and full', 1, true, true, true),
  ('suspended', 'Suspended', 'harmonic_color', 'Unresolved harmonic tension from suspended chord voicings', 2, true, false, false),
  ('gospel-rich', 'Gospel Rich', 'harmonic_color', 'Warm choral harmonies and call-and-response influenced by gospel', 1, true, true, true),
  ('melancholic', 'Melancholic', 'harmonic_color', 'Chord progressions that evoke sadness or longing', 1, true, true, true),
  ('bright', 'Bright', 'harmonic_color', 'High-frequency harmonic content that feels open and airy', 2, true, false, false),
  ('cinematic', 'Cinematic', 'harmonic_color', 'Orchestral or filmic harmonic language suggesting visual narrative', 1, true, true, true),
  ('static-vamp', 'Static Vamp', 'harmonic_color', 'One or two chords repeated cyclically with minimal movement', 3, false, false, false),
  ('nostalgic', 'Nostalgic', 'harmonic_color', 'Chord progressions evoking memory and a longing for the past', 1, true, true, true),
  ('chant-like', 'Chant-Like', 'melodic_character', 'Repetitive melodic cells with a ritual or incantatory quality', 2, true, false, false),
  ('airy', 'Airy', 'melodic_character', 'Light, open melodic phrases with space and breathing room', 1, true, true, true),
  ('conversational', 'Conversational', 'melodic_character', 'Melodic phrasing that mimics natural speech cadences', 2, true, false, false),
  ('hook-forward', 'Hook Forward', 'melodic_character', 'Immediately memorable melodic hook is the central feature', 2, true, false, false),
  ('leap-heavy', 'Leap Heavy', 'melodic_character', 'Melody moves frequently in large intervals rather than stepwise motion', 3, false, false, false),
  ('repetitive', 'Repetitive', 'melodic_character', 'Melodic phrases loop or return with minimal variation', 2, true, false, false),
  ('silky', 'Silky', 'melodic_character', 'Smooth, legato melodic movement with seamless phrase connections', 1, true, true, true),
  ('angular', 'Angular', 'melodic_character', 'Jagged, unpredictable melodic contour that avoids smooth curves', 2, true, false, false),
  ('anthemic', 'Anthemic', 'melodic_character', 'Large-scale melodic gesture designed for collective singing', 1, true, true, true),
  ('intimate', 'Intimate', 'melodic_character', 'Close, personal melodic delivery that feels confessional', 1, true, true, true),
  ('breathy', 'Breathy', 'vocal_character', 'Audible breath in vocal delivery creating closeness and vulnerability', 1, true, true, true),
  ('commanding', 'Commanding', 'vocal_character', 'Authoritative vocal presence that demands full attention', 2, true, false, false),
  ('restrained-vocal', 'Restrained', 'vocal_character', 'Held-back delivery that conveys emotion through understatement', 2, true, false, false),
  ('falsetto-led', 'Falsetto Led', 'vocal_character', 'Primary vocal range in falsetto register, light and ethereal', 1, true, true, true),
  ('layered', 'Layered', 'vocal_character', 'Multiple vocal tracks stacked to create dense harmonic texture', 2, true, false, false),
  ('talk-sung', 'Talk-Sung', 'vocal_character', 'Vocal delivery between speaking and singing, melodic but speech-like', 2, true, false, false),
  ('rhythmic', 'Rhythmic', 'vocal_character', 'Vocal phrasing that emphasizes rhythmic precision over pitch', 2, true, false, false),
  ('emotionally-direct', 'Emotionally Direct', 'vocal_character', 'Vocal performance that makes no attempt to conceal its emotional content', 2, true, false, false),
  ('cool-toned', 'Cool Toned', 'vocal_character', 'Detached, slightly aloof vocal quality that suggests emotional distance', 3, false, false, false),
  ('raw', 'Raw', 'vocal_character', 'Unpolished, exposed vocal performance prioritizing feeling over technique', 1, true, true, true),
  ('yearning', 'Yearning', 'vocal_character', 'Vocal tone saturated with longing, desire or emotional reaching', 1, true, true, true),
  ('glossy', 'Glossy', 'texture', 'Highly polished production surface with smooth, reflective quality', 1, true, true, true),
  ('grainy', 'Grainy', 'texture', 'Textured production with visible noise and analog imperfection', 1, true, true, true),
  ('neon', 'Neon', 'texture', 'Bright, synthetic texture with electric color and high contrast', 1, true, true, true),
  ('analog', 'Analog', 'texture', 'Warm, slightly imperfect quality of recorded-to-tape sound', 1, true, true, true),
  ('lo-fi', 'Lo-Fi', 'texture', 'Deliberately low-fidelity production with warmth and nostalgia', 1, true, true, true),
  ('polished', 'Polished', 'texture', 'Highly produced, clean mix with professional finish', 2, true, false, false),
  ('hazy', 'Hazy', 'texture', 'Blurred, soft-focus sonic texture suggesting dreamlike states', 1, true, true, true),
  ('saturated', 'Saturated', 'texture', 'Heavily compressed or driven texture with maximum sonic density', 2, true, false, false),
  ('sparse', 'Sparse', 'texture', 'Minimal arrangement where silence and space carry as much weight as sound', 1, true, true, true),
  ('lush-texture', 'Lush', 'texture', 'Dense, layered production that feels rich and enveloping', 1, true, true, true),
  ('metallic', 'Metallic', 'texture', 'Bright, hard-edged texture with a cold, industrial character', 2, true, false, false),
  ('warm', 'Warm', 'texture', 'Round, full-bodied sonic texture with comfortable low-mid presence', 1, true, true, true),
  ('immediate-impact', 'Immediate Impact', 'arrangement_energy_arc', 'Full energy delivered from the opening bars with no build-up required', 2, true, false, false),
  ('slow-build', 'Slow Build', 'arrangement_energy_arc', 'Gradual accumulation of elements building toward a peak moment', 1, true, true, true),
  ('sustained-drive', 'Sustained Drive', 'arrangement_energy_arc', 'Consistent energy level maintained throughout without major peaks', 2, true, false, false),
  ('explosive-chorus', 'Explosive Chorus', 'arrangement_energy_arc', 'Dramatic energy increase at chorus creates cathartic impact', 2, true, false, false),
  ('hypnotic-loop', 'Hypnotic Loop', 'arrangement_energy_arc', 'Repeating structural pattern designed to induce meditative states', 1, true, true, true),
  ('late-night-cruise', 'Late Night Cruise', 'arrangement_energy_arc', 'Steady, unhurried energy arc suited to nocturnal listening', 1, true, true, true),
  ('euphoric-lift', 'Euphoric Lift', 'arrangement_energy_arc', 'Production elements converge to create a feeling of elevation', 1, true, true, true),
  ('tension-release', 'Tension Release', 'arrangement_energy_arc', 'Deliberate harmonic or dynamic tension resolved at key moments', 2, true, false, false),
  ('simmering', 'Simmering', 'arrangement_energy_arc', 'Low-level energy that suggests intensity without fully releasing it', 2, true, false, false),
  ('full-bloom', 'Full Bloom', 'arrangement_energy_arc', 'All arrangement elements present simultaneously at maximum richness', 2, true, false, false),
  ('wistful', 'Wistful', 'emotional_tone', 'Tender longing for something past or out of reach', 1, true, true, true),
  ('triumphant', 'Triumphant', 'emotional_tone', 'Celebratory emotional quality suggesting victory or overcoming', 1, true, true, true),
  ('lonely', 'Lonely', 'emotional_tone', 'Emotional isolation rendered through sonic choices and lyrical themes', 1, true, true, true),
  ('seductive', 'Seductive', 'emotional_tone', 'Alluring, sensual emotional register designed to attract', 1, true, true, true),
  ('swaggering', 'Swaggering', 'emotional_tone', 'Confident, self-assured energy that borders on arrogance', 1, true, true, true),
  ('devotional', 'Devotional', 'emotional_tone', 'Deep reverence and dedication conveyed through musical delivery', 1, true, true, true),
  ('restless', 'Restless', 'emotional_tone', 'Anxious forward motion, unable to settle or find stillness', 1, true, true, true),
  ('playful', 'Playful', 'emotional_tone', 'Light, fun emotional register without weight or self-seriousness', 1, true, true, true),
  ('cold', 'Cold', 'emotional_tone', 'Emotional detachment rendered through sparse, clinical production', 1, true, true, true),
  ('glamorous', 'Glamorous', 'emotional_tone', 'Aspirational, elevated emotional quality associated with luxury', 1, true, true, true),
  ('tender', 'Tender', 'emotional_tone', 'Gentle, careful emotional handling of vulnerable subject matter', 1, true, true, true),
  ('nocturnal', 'Nocturnal', 'emotional_tone', 'Late-night, introspective atmosphere suited to darkness and solitude', 1, true, true, true),
  ('euphoric', 'Euphoric', 'emotional_tone', 'Overwhelming positive emotional intensity approaching transcendence', 1, true, true, true),
  ('blog-era-rap', 'Blog Era Rap', 'era_lineage', 'Indie rap and alternative hip-hop aesthetic of 2007–2012', 1, true, true, true),
  ('80s-revival', '80s Revival', 'era_lineage', 'Production that consciously references 1980s synth and drum machine aesthetics', 1, true, true, true),
  ('90s-r-and-b', '90s R&B', 'era_lineage', 'Production lineage rooted in 1990s R&B production techniques', 1, true, true, true),
  ('y2k-club', 'Y2K Club', 'era_lineage', 'Early 2000s club music aesthetic with maximalist digital production', 1, true, true, true),
  ('neo-soul', 'Neo-Soul', 'era_lineage', 'Late 90s/early 2000s soul revival with jazz and hip-hop elements', 1, true, true, true),
  ('indie-sleaze', 'Indie Sleaze', 'era_lineage', 'Early 2010s indie rock aesthetic with a raw, hedonistic character', 1, true, true, true),
  ('trap-soul', 'Trap Soul', 'era_lineage', 'Fusion of trap production and R&B emotional depth', 1, true, true, true),
  ('synth-pop', 'Synth-Pop', 'era_lineage', 'Synthesizer-led pop with clean, electronic production values', 1, true, true, true),
  ('quiet-storm', 'Quiet Storm', 'era_lineage', 'Smooth, late-night R&B format rooted in 1970s–80s soft soul', 1, true, true, true),
  ('electro-pop', 'Electro-Pop', 'era_lineage', 'Dance-oriented electronic pop with programmed rhythms and synth leads', 1, true, true, true),
  ('night-drive', 'Night Drive', 'environment_imagery', 'Music suited to driving alone at night through lit city streets', 1, true, true, true),
  ('club-floor', 'Club Floor', 'environment_imagery', 'Music designed for the energy and movement of a dance floor', 1, true, true, true),
  ('headphones-alone', 'Headphones Alone', 'environment_imagery', 'Intimate music best experienced in private with focused listening', 1, true, true, true),
  ('rooftop-city', 'Rooftop City', 'environment_imagery', 'Elevated, urban atmosphere with skyline energy and open air', 1, true, true, true),
  ('summer-daylight', 'Summer Daylight', 'environment_imagery', 'Warm, bright outdoor setting with summer heat and long hours', 1, true, true, true),
  ('rainy-street', 'Rainy Street', 'environment_imagery', 'Wet pavement, grey light, introspective urban atmosphere', 1, true, true, true),
  ('after-hours', 'After Hours', 'environment_imagery', 'Post-midnight energy, blurred edges, intimate and slightly reckless', 1, true, true, true),
  ('house-party', 'House Party', 'environment_imagery', 'Social, celebratory domestic environment with informal energy', 1, true, true, true),
  ('pregame', 'Pregame', 'listener_use_case', 'Music that builds anticipation and energy before going out', 1, true, true, true),
  ('late-night-walk', 'Late Night Walk', 'listener_use_case', 'Reflective music suited to solitary walking after dark', 1, true, true, true),
  ('dancefloor', 'Dancefloor', 'listener_use_case', 'Music optimized for physical movement and collective dancing', 1, true, true, true),
  ('windows-down', 'Windows Down', 'listener_use_case', 'Music for driving fast with the windows open and volume up', 1, true, true, true),
  ('flirtation', 'Flirtation', 'listener_use_case', 'Music with sensual or playful energy suited to attraction', 1, true, true, true),
  ('reflective-commute', 'Reflective Commute', 'listener_use_case', 'Music for inward thinking during transit between places', 1, true, true, true)
ON CONFLICT (slug) DO UPDATE SET
  label          = EXCLUDED.label,
  category       = EXCLUDED.category,
  description    = EXCLUDED.description,
  tier           = EXCLUDED.tier,
  is_public      = EXCLUDED.is_public,
  is_clickable   = EXCLUDED.is_clickable,
  is_seo_enabled = EXCLUDED.is_seo_enabled;
